//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licorera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public int IIDCARRITO { get; set; }
        public Nullable<int> IIDPRODUCTO { get; set; }
        public Nullable<int> IIDUSUARIO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
